# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 23:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annuaire', '0002_auto_20160331_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('filter', models.IntegerField(default=0, verbose_name='filtre')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('toc', models.BooleanField(default=False, verbose_name='Table des mati\xe8res')),
                ('introduction', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.Mailing')),
            ],
        ),
        migrations.CreateModel(
            name='MailingLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('link', models.CharField(max_length=200)),
                ('accessed', models.BooleanField(default=False)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.Mailing')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annuaire.Person')),
            ],
        ),
        migrations.CreateModel(
            name='MailingRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('accessed', models.BooleanField(default=False)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.Mailing')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annuaire.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PortalError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='titre')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('url', models.CharField(max_length=500, verbose_name='url')),
                ('referer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Referrer')),
                ('browser_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Navigateur')),
                ('client_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse du client')),
                ('exception', models.TextField(verbose_name='Exception')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='commentaire')),
                ('issue', models.CharField(blank=True, max_length=20, null=True, verbose_name='Issue')),
                ('fixed', models.BooleanField(default=False, verbose_name='corrig\xe9')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
        ),
    ]
