# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage', '0001_initial'),
        ('annuaire', '0002_auto_20160331_0126'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingitem',
            name='newsitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsItem'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_approved', to='annuaire.Person'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_created', to='annuaire.Person'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='mail_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.Filter', verbose_name='Destinataires'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_modified', to='annuaire.Person'),
        ),
    ]
