# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annuaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifi\xe9 pour la derni\xe8re fois \xe0')),
                ('old_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name=b'old id')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nom')),
                ('line1', models.CharField(blank=True, max_length=50, null=True, verbose_name='ligne 1')),
                ('line2', models.CharField(blank=True, max_length=100, null=True, verbose_name='ligne 2')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='code postal')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='ville')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='num\xe9ro de t\xe9l\xe9phone')),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='fax')),
                ('web_site', models.CharField(blank=True, max_length=100, null=True, verbose_name='site internet')),
                ('is_valid', models.BooleanField(default=True, verbose_name='est valide')),
                ('is_a_proposal', models.BooleanField(default=False, verbose_name='est une proposition')),
                ('modification_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annuaire.Country', verbose_name='pays')),
                ('last_change_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_changed_office', to='annuaire.Person', verbose_name='Auteur de la derni\xe8re modification')),
                ('modification_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Office')),
            ],
            options={
                'verbose_name': '\xe9tablissement',
                'verbose_name_plural': '\xe9tablissements',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifi\xe9 pour la derni\xe8re fois \xe0')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('size', models.IntegerField(blank=True, choices=[(0, 'Unipersonelle (0)'), (1, 'TPE (1-9)'), (2, 'PME (10-499)'), (3, 'GE (500+)'), (10, 'Inconnu')], null=True, verbose_name='taille')),
                ('short_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='description courte')),
                ('long_description', models.TextField(blank=True, null=True, verbose_name='description longue')),
                ('employment_agency', models.BooleanField(default=False, verbose_name='cabinet de recrutement')),
                ('is_a_proposal', models.BooleanField(default=False, verbose_name='est une proposition')),
                ('is_valid', models.BooleanField(default=True, verbose_name='est valide')),
                ('modification_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'entreprise',
            },
        ),
        migrations.CreateModel(
            name='OrganizationActivityField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='domaine')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='code')),
                ('keywords', models.CharField(max_length=100, verbose_name='mots cl\xe9s')),
                ('label', models.CharField(max_length=100, verbose_name='libell\xe9')),
            ],
            options={
                'ordering': ['label'],
                'verbose_name': "Domaine d'activit\xe9",
            },
        ),
        migrations.CreateModel(
            name='OrganizationSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, verbose_name='taille')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='activity_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='organizations.OrganizationActivityField', verbose_name="Domaine d'activit\xe9"),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_change_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_changed_organization', to='annuaire.Person', verbose_name='Auteur de la derni\xe8re modification'),
        ),
        migrations.AddField(
            model_name='organization',
            name='modification_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
        migrations.AddField(
            model_name='office',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='organizations.Organization', verbose_name='entreprise'),
        ),
    ]
