# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annuaire', '0002_auto_20160331_0126'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifi\xe9 pour la derni\xe8re fois \xe0')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='R\xe9ference')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('experience', models.CharField(blank=True, max_length=50, null=True, verbose_name='Experience')),
                ('contract_type', models.IntegerField(choices=[(0, b'CDI'), (1, b'CDD'), (2, b'Stage')], verbose_name='Type de Contrat')),
                ('contact_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nom du contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='courriel')),
                ('checked_by_secretariat', models.BooleanField(default=False, verbose_name='v\xe9rifi\xe9 par le secr\xe9tariat')),
                ('obsolete', models.BooleanField(default=False, verbose_name="L'offre d'emploi est obsolete")),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField(editable=False)),
                ('activity_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='organizations.OrganizationActivityField', verbose_name="Domaine d'activit\xe9")),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_offers_created', to='annuaire.Person', verbose_name='auteur')),
                ('last_change_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_changed_joboffer', to='annuaire.Person', verbose_name='Auteur de la derni\xe8re modification')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_offers_modified', to='annuaire.Person', verbose_name='auteur')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Office')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': "Offre d'emploi",
            },
        ),
        migrations.CreateModel(
            name='JobOfferView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.JobOffer')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annuaire.Person')),
            ],
        ),
    ]
