# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifi\xe9 pour la derni\xe8re fois \xe0')),
                ('line1', models.CharField(max_length=50, verbose_name='adresse ligne 1')),
                ('line2', models.CharField(blank=True, max_length=100, null=True, verbose_name='adresse ligne 2')),
                ('zip_code', models.CharField(max_length=20, verbose_name='code postal')),
                ('city', models.CharField(max_length=50, verbose_name='ville')),
                ('confidentiality', models.IntegerField(choices=[(0, 'public'), (1, 'priv\xe9')], default=0, verbose_name='confidentialit\xe9')),
                ('confidential', models.BooleanField(default=False, verbose_name='confidentiel')),
                ('is_valid', models.BooleanField(default=True, verbose_name='est valide')),
            ],
            options={
                'verbose_name': 'Adresse',
            },
        ),
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
            ],
            options={
                'verbose_name': "type d'adresse",
                'verbose_name_plural': "types d'adresse",
            },
        ),
        migrations.CreateModel(
            name='AIn7Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifi\xe9 pour la derni\xe8re fois \xe0')),
                ('children_count', models.IntegerField(blank=True, null=True, verbose_name="nombre d'enfants")),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Surnom')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=b'data/avatar', verbose_name='avatar')),
                ('receive_job_offers', models.BooleanField(default=False, verbose_name="Recevoir les offres d'emploi par courriel")),
            ],
            options={
                'ordering': ['person'],
                'verbose_name': 'Membre AIn7',
            },
        ),
        migrations.CreateModel(
            name='CeremonialDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceremonial_duty', models.CharField(max_length=200, verbose_name='fonction honorifique')),
            ],
            options={
                'ordering': ['ceremonial_duty'],
                'verbose_name': 'fonction honorifique',
                'verbose_name_plural': 'fonctions honorifiques',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifi\xe9 pour la derni\xe8re fois \xe0')),
                ('name', models.CharField(max_length=20, verbose_name=b'name')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('web_site', models.URLField(blank=True, max_length=50, null=True, verbose_name='site internet')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='courriel')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=b'data/', verbose_name='ic\xf4ne')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': 'club',
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(blank=True, max_length=50, null=True, verbose_name='fonction')),
                ('begin', models.IntegerField(blank=True, null=True, verbose_name='Date de d\xe9but')),
                ('end', models.IntegerField(blank=True, null=True, verbose_name='Date de fin')),
            ],
            options={
                'ordering': ['begin'],
                'verbose_name': 'adh\xe9sion club',
                'verbose_name_plural': 'adh\xe9sions clubs',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('nationality', models.CharField(max_length=50, verbose_name='nationalit\xe9')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'pays',
                'verbose_name_plural': 'pays',
            },
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decoration', models.CharField(max_length=200, verbose_name='d\xe9coration')),
            ],
            options={
                'ordering': ['decoration'],
                'verbose_name': 'd\xe9coration',
            },
        ),
        migrations.CreateModel(
            name='EducationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifi\xe9 pour la derni\xe8re fois \xe0')),
                ('school', models.CharField(blank=True, max_length=150, null=True, verbose_name='\xe9cole')),
                ('diploma', models.CharField(blank=True, max_length=150, null=True, verbose_name='dipl\xf4me')),
                ('details', models.TextField(blank=True, null=True, verbose_name='description')),
                ('begin', models.IntegerField(blank=True, null=True, verbose_name='d\xe9but (ann\xe9e)')),
                ('end', models.IntegerField(blank=True, null=True, verbose_name='fin (ann\xe9e)')),
            ],
            options={
                'ordering': ['-begin'],
                'verbose_name': 'Entr\xe9e du CV partie "Formation"',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='courriel')),
                ('confidentiality', models.IntegerField(choices=[(0, 'public'), (1, 'priv\xe9')], default=0, verbose_name='confidentialit\xe9')),
                ('confidential', models.BooleanField(default=False, verbose_name='confidentiel')),
                ('preferred_email', models.BooleanField(default=False, verbose_name='favori')),
            ],
            options={
                'verbose_name': 'courriel',
            },
        ),
        migrations.CreateModel(
            name='InstantMessaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, b'ICQ'), (2, b'MSN'), (3, b'AIM'), (4, b'Yahoo'), (5, b'Jabber'), (6, b'Gadu-Gadu'), (7, b'Skype')], verbose_name='type')),
                ('identifier', models.CharField(max_length=40, verbose_name='identifiant')),
                ('confidentiality', models.IntegerField(choices=[(0, 'public'), (1, 'priv\xe9')], default=0, verbose_name='confidentialit\xe9')),
                ('confidential', models.BooleanField(default=False, verbose_name='confidentiel')),
            ],
            options={
                'verbose_name': 'messagerie instantan\xe9e',
            },
        ),
        migrations.CreateModel(
            name='LeisureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifi\xe9 pour la derni\xe8re fois \xe0')),
                ('title', models.CharField(max_length=50, verbose_name='Titre')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='D\xe9tail')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Loisirs',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='\xe9tat')),
            ],
            options={
                'verbose_name': 'statut marital',
            },
        ),
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
            ],
            options={
                'verbose_name': 'type de membre',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifi\xe9 pour la derni\xe8re fois \xe0')),
                ('old_id', models.IntegerField(blank=True, null=True, verbose_name=b'old id')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('first_name', models.CharField(max_length=50, verbose_name='Pr\xe9nom')),
                ('complete_name', models.CharField(max_length=50, verbose_name='Nom complet')),
                ('maiden_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nom de jeune fille')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('sex', models.CharField(choices=[(b'M', 'Masculin'), (b'F', 'F\xe9minin')], max_length=1, verbose_name='sexe')),
                ('validated', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'verbose_name': 'personne',
            },
        ),
        migrations.CreateModel(
            name='PersonPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifi\xe9 pour la derni\xe8re fois \xe0')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='date de d\xe9c\xe8s')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'ordering': ['person'],
                'verbose_name': 'Donn\xe9es personnelles',
            },
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
            ],
            options={
                'verbose_name': 'type de personne',
                'verbose_name_plural': 'types de personne',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifi\xe9 pour la derni\xe8re fois \xe0')),
                ('number', models.CharField(max_length=30, verbose_name='nombre')),
                ('type', models.IntegerField(choices=[(1, 'T\xe9l. fixe'), (2, 'Fax'), (3, 'T\xe9l. portable')], default=1, verbose_name='type')),
                ('confidentiality', models.IntegerField(choices=[(0, 'public'), (1, 'priv\xe9')], default=0, verbose_name='confidentialit\xe9')),
                ('confidential', models.BooleanField(default=False, verbose_name='confidentiel')),
            ],
            options={
                'verbose_name': 'num\xe9ro de t\xe9l\xe9phone',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifi\xe9 pour la derni\xe8re fois \xe0')),
                ('fonction', models.CharField(blank=True, max_length=80, null=True, verbose_name='fonction')),
                ('service', models.CharField(blank=True, max_length=80, null=True, verbose_name='service')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='t\xe9l\xe9phone')),
                ('is_regie', models.BooleanField(default=False, verbose_name="R\xe9gie \xe0 l'ext\xe9rieur")),
                ('begin', models.IntegerField(blank=True, null=True, verbose_name='ann\xe9e de d\xe9but')),
                ('end', models.IntegerField(blank=True, null=True, verbose_name='fin (ann\xe9e)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('ain7member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='annuaire.AIn7Member')),
                ('last_change_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_changed_position', to='annuaire.Person', verbose_name='Auteur de la derni\xe8re modification')),
            ],
            options={
                'ordering': ['-begin'],
                'verbose_name': 'exp\xe9rience professionnelle',
            },
        ),
        migrations.CreateModel(
            name='ProfileEditKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField(editable=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annuaire.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['year', 'track'],
                'verbose_name': 'Ann\xe9e de promotion',
            },
        ),
        migrations.CreateModel(
            name='PromoYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='ann\xe9e')),
            ],
            options={
                'verbose_name': 'Ann\xe9e',
            },
        ),
        migrations.CreateModel(
            name='PublicationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifi\xe9 pour la derni\xe8re fois \xe0')),
                ('title', models.CharField(max_length=50, verbose_name='Titre')),
                ('details', models.TextField(blank=True, null=True, verbose_name='D\xe9tail')),
                ('date', models.DateField()),
                ('ain7member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='annuaire.AIn7Member')),
                ('last_change_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_changed_publicationitem', to='annuaire.Person', verbose_name='Auteur de la derni\xe8re modification')),
            ],
            options={
                'verbose_name': 'Publication et brevet',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='nom')),
                ('initials', models.CharField(blank=True, max_length=20, null=True, verbose_name='initiales')),
                ('line1', models.CharField(blank=True, max_length=50, null=True, verbose_name='ligne 1')),
                ('line2', models.CharField(blank=True, max_length=100, null=True, verbose_name='ligne 2')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='code postal')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='ville')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='num\xe9ro de t\xe9l\xe9phone')),
                ('web_site', models.CharField(blank=True, max_length=100, null=True, verbose_name='site internet')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='courriel')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annuaire.Country', verbose_name='pays')),
            ],
            options={
                'verbose_name': '\xe9cole',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fili\xe8re')),
                ('initials', models.CharField(blank=True, max_length=10, null=True, verbose_name='initiales')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='courriel')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='annuaire.School', verbose_name='\xe9cole')),
            ],
            options={
                'verbose_name': 'Fili\xe8re',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date de d\xe9but')),
                ('client_host', models.CharField(blank=True, max_length=256, null=True)),
                ('browser_info', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annuaire.Person')),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': 'activit\xe9 utilisateur',
                'verbose_name_plural': 'activit\xe9s des utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='site internet')),
                ('type', models.IntegerField(choices=[(0, b'link'), (1, b'blog'), (2, b'gallery'), (3, b'linkedin'), (4, b'viadeo'), (5, b'flickr'), (6, b'facebook'), (7, b'twitter'), (8, b'myspace'), (100, b'Other')], verbose_name='type')),
                ('confidentiality', models.IntegerField(choices=[(0, 'public'), (1, 'priv\xe9')], default=0, verbose_name='confidentialit\xe9')),
                ('confidential', models.BooleanField(default=False, verbose_name='confidentiel')),
                ('blog_is_agregated_on_planet', models.BooleanField(default=False, verbose_name='Blog agr\xe9g\xe9 sur le Planet')),
                ('person', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='web_sites', to='annuaire.Person')),
            ],
            options={
                'verbose_name': 'site internet',
            },
        ),
        migrations.AddField(
            model_name='promo',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='annuaire.Track', verbose_name='Fili\xe8re'),
        ),
        migrations.AddField(
            model_name='promo',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promosyear', to='annuaire.PromoYear', verbose_name='Ann\xe9e de promotion'),
        ),
    ]
